// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPMnHJnMQp0Ksc5fYJF51cRdDPfOVGsw',
    appId: '1:700062530532:web:72d4941a934bf3795025f1',
    messagingSenderId: '700062530532',
    projectId: 'sc-worldchitchat',
    authDomain: 'sc-worldchitchat.firebaseapp.com',
    storageBucket: 'sc-worldchitchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MJT6u3Pb9zW8kcqZkpTdhSdMROgX4no',
    appId: '1:700062530532:android:3225f72638613ee45025f1',
    messagingSenderId: '700062530532',
    projectId: 'sc-worldchitchat',
    storageBucket: 'sc-worldchitchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpta93O0gClbACdDj-zsJq68xc57PEh8',
    appId: '1:700062530532:ios:c7952921ba79a6d05025f1',
    messagingSenderId: '700062530532',
    projectId: 'sc-worldchitchat',
    storageBucket: 'sc-worldchitchat.appspot.com',
    iosBundleId: 'com.stcache.dazzelyChatTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpta93O0gClbACdDj-zsJq68xc57PEh8',
    appId: '1:700062530532:ios:0745a65a8f8d8ebf5025f1',
    messagingSenderId: '700062530532',
    projectId: 'sc-worldchitchat',
    storageBucket: 'sc-worldchitchat.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvPMnHJnMQp0Ksc5fYJF51cRdDPfOVGsw',
    appId: '1:700062530532:web:507c7bcadcd1fc0e5025f1',
    messagingSenderId: '700062530532',
    projectId: 'sc-worldchitchat',
    authDomain: 'sc-worldchitchat.firebaseapp.com',
    storageBucket: 'sc-worldchitchat.appspot.com',
  );

}