require 'json'

encryption_filename = "encryption_key.json"
encryption_file = File.read("./#{encryption_filename}")
key_hash = JSON.parse(encryption_file)

namespace :dev do

  desc "Run dart build_runner secure_dotenv : type - build or watch (default: watch)"
  task :gen_envs, [:type] do |task, args|
    args.with_defaults(type: "watch")
    
    is_watch = args[:type] == "watch"
    use_polling_watcher = is_watch ? "--use-polling-watcher " : ""
    define_secure_dotenv_variable = "--define secure_dotenv_generator:secure_dotenv="
    command =
      "dart run build_runner " \
      "#{args[:type]} " \
      "--delete-conflicting-outputs " \
      "#{use_polling_watcher}" \
      "#{define_secure_dotenv_variable}ENCRYPTION_KEY=#{key_hash['ENCRYPTION_KEY']} " \
      "#{define_secure_dotenv_variable}IV=#{key_hash['IV']} " \
      "#{define_secure_dotenv_variable}OUTPUT_FILE=#{encryption_filename}"
    
    puts "Running ':gen_envs' task..."
    puts "Command: #{command}\n"
    system command
  end
end

namespace :release do

  desc "Build ipa for staging"
  task :build_ios_stage do
    command = "flutter build ipa --obfuscate --split-debug-info=./build_debug_info --dart-define=ENV=stage --dart-define-from-file=encryption_key.json"
    system command
  end
end