// Besides kMaterialSupportedLanguages, Flutter also supports these additional
// specific language variations, otherwise it uses the generic version.
// * Not currently being used *

const additionalLanguageRegions = [
  'de_CH',
  'en_AU',
  'en_CA',
  'en_GB',
  'en_IE',
  'en_IN',
  'en_NZ',
  'en_SG',
  'en_ZA',
  'es_419',
  'es_AR',
  'es_BO',
  'es_CL',
  'es_CO',
  'es_CR',
  'es_DO',
  'es_EC',
  'es_GT',
  'es_HN',
  'es_MX',
  'es_NI',
  'es_PA',
  'es_PE',
  'es_PR',
  'es_PY',
  'es_SV',
  'es_US',
  'es_UY',
  'es_VE',
  'fr_CA',
  'pt_PT',
  'sr_Cyrl',
  'sr_Latn',
  'zh_Hans',
  'zh_Hant',
  'zh_Hant_HK',
  'zh_Hant_TW',
];
